version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=enigma
      - POSTGRES_DB=cloud_vendor
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5434:5432'

  cloudvendor:
    container_name: cloudvendor_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/cloud_vendor
      - SPRING_DATASOURCE_USERNAME=enigma
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
